# Generated by Django 5.2.7 on 2025-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
